#!/bin/sh
cd $CMSSW_BASE/L1Ntuple/2021_01_04
for job in job*; do HOStudy $job/L1Ntuple.root L1Histogram${job:3}; done
hadd L1Histogram.root L1Histogram*
cd $CMSSW_BASE/src
python3 Plotting/Plotter/python/histPlotter.py -i $CMSSW_BASE/L1Ntuple/2021_01_04/L1Histogram.root
