#!/bin/sh
INPUTFILE=$1
TARGETDIR=$2
JOBNUMBER=$3
export X509_USER_PROXY=/nfs/dust/cms/user/wiens/x509up

source /etc/profile
source /cvmfs/cms.cern.ch/cmsset_default.sh
source /cvmfs/grid.desy.de/etc/profile.d/grid-ui-env.sh

module use -a /afs/desy.de/group/cms/modulefiles/
module load cmssw
cd $TARGETDIR/src
export SCRAM_ARCH=slc6_amd64_gcc700;
eval `scramv1 runtime -sh`;

mkdir -p $TARGETDIR/L1Ntuple/`date +"%Y_%m_%d"`/job_$JOBNUMBER
cd $TARGETDIR/L1Ntuple/`date +"%Y_%m_%d"`/job_$JOBNUMBER

cmsDriver.py l1Ntuple -s RAW2DIGI --python_filename=data.py --no_output --era=Run2_2018 --data --conditions=110X_dataRun2_v12 --customise=L1Trigger/Configuration/customiseReEmul.L1TReEmulFromRAW --customise=L1Trigger/L1TNtuples/customiseL1Ntuple.L1NtupleAODRAWEMU --customise=L1Trigger/Configuration/customiseSettings.L1TSettingsToCaloParams_2018_v1_4_1 --filein=$INPUTFILE
#cmsRun -e -j l1NtupleReport.xml /nfs/dust/cms/user/wiens/CMSSW/HO/CMSSW_11_0_2/src/HOAnalysis/HOL1/python/data.py
